"""run_gpu(seed_shapes=...) replays each seeded ellipse onto canvas
before entering the greedy loop. Final shapes list = seeded +
newly-generated. Total count = num_shapes parameter (NOT
len(seeded) + num_shapes — num_shapes is the TARGET).
"""
from __future__ import annotations

import pytest

torch = pytest.importorskip("torch")
np = pytest.importorskip("numpy")


def _make_target(h=32, w=32):
    arr = np.zeros((h, w, 3), dtype=np.uint8)
    arr[:, :w // 2] = (200, 80, 80)
    arr[:, w // 2:] = (80, 80, 200)
    return arr


def _ellipse(x, y):
    return {
        "type": "rotated_ellipse",
        "x": float(x), "y": float(y),
        "rx": 4.0, "ry": 4.0, "angle": 0.0,
        "color": [128, 128, 128, 255],
    }


def test_seed_only_returns_seeded_unchanged():
    """num_shapes equals len(seeded) → loop runs 0 iterations →
    output is exactly the seeded shapes."""
    from forza_abyss_painter.shapegen.gpu.engine import GPUConfig, run_gpu
    target = _make_target()
    seed = [_ellipse(8, 16), _ellipse(16, 16), _ellipse(24, 16)]
    cfg = GPUConfig(
        num_shapes=3,           # equal to len(seed)
        random_samples=64,
        bbox_local=True,
        joint_polish_steps=0,   # skip polish for speed
        refill_dead_shapes=False,
    )
    shapes_out, _canvas = run_gpu(
        target_rgb=target, cfg=cfg, alpha_mask=None,
        progress_every=0, checkpoint_cb=None, checkpoint_every=0,
        seed_shapes=seed,
    )
    assert len(shapes_out) == 3
    for i, (a, b) in enumerate(zip(seed, shapes_out)):
        for key in ("x", "y", "rx", "ry", "angle"):
            assert abs(a[key] - b[key]) < 1e-6, (
                f"seeded shape {i} key {key} mutated: "
                f"in={a[key]} out={b[key]}"
            )


def test_seed_plus_generated_produces_target_count():
    """num_shapes=5, len(seeded)=3 → output has 5 shapes; first 3
    bit-identical to seed; last 2 generated by greedy."""
    from forza_abyss_painter.shapegen.gpu.engine import GPUConfig, run_gpu
    target = _make_target()
    seed = [_ellipse(8, 16), _ellipse(16, 16), _ellipse(24, 16)]
    cfg = GPUConfig(
        num_shapes=5,
        random_samples=64,
        bbox_local=True,
        joint_polish_steps=0,
        refill_dead_shapes=False,
    )
    shapes_out, _canvas = run_gpu(
        target_rgb=target, cfg=cfg, alpha_mask=None,
        progress_every=0, checkpoint_cb=None, checkpoint_every=0,
        seed_shapes=seed,
    )
    assert len(shapes_out) == 5
    for i in range(3):
        for key in ("x", "y", "rx", "ry", "angle"):
            assert abs(seed[i][key] - shapes_out[i][key]) < 1e-6


def test_no_seed_unchanged_behavior():
    """seed_shapes=None must produce identical output to omitting the
    kwarg (back-compat)."""
    from forza_abyss_painter.shapegen.gpu.engine import GPUConfig, run_gpu
    target = _make_target()
    cfg = GPUConfig(
        num_shapes=2,
        random_samples=64,
        seed=42,                # fixed seed → deterministic
        bbox_local=True,
        joint_polish_steps=0,
        refill_dead_shapes=False,
    )
    out_default, _ = run_gpu(
        target_rgb=target, cfg=cfg, alpha_mask=None,
        progress_every=0, checkpoint_cb=None, checkpoint_every=0,
    )
    out_none, _ = run_gpu(
        target_rgb=target, cfg=cfg, alpha_mask=None,
        progress_every=0, checkpoint_cb=None, checkpoint_every=0,
        seed_shapes=None,
    )
    assert len(out_default) == 2
    assert len(out_none) == 2
