from __future__ import annotations

from dataclasses import dataclass, field, asdict
from datetime import datetime, timezone
from typing import Iterable

from forza_abyss_painter.shapegen.shapes import Shape, shape_from_json

FD6_FORMAT = "fd6.shapes"
FD6_VERSION = 1


@dataclass
class FD6Document:
    """v1 of the FD6 shape JSON document. See README for schema details."""

    format: str = FD6_FORMAT
    version: int = FD6_VERSION
    source_image: str = ""
    image_size: tuple[int, int] = (0, 0)  # (width, height)
    shape_count: int = 0
    generated_at: str = ""
    profile: str = ""
    # True when the JSON was generated with sticker mode (transparent backdrop —
    # "Add white background to transparent images" was UNCHECKED). Default False
    # for backwards compat with older JSONs that pre-date this field. Affects
    # how the GUI re-renders the preview on Upload JSON: sticker JSONs get a
    # transparent preview, non-sticker JSONs get a white canvas as before.
    sticker_mode: bool = False
    shapes: list[dict] = field(default_factory=list)

    def to_dict(self) -> dict:
        d = asdict(self)
        d["image_size"] = list(self.image_size)
        return d

    @classmethod
    def from_dict(cls, data: dict) -> "FD6Document":
        """Load an FD6Document from a parsed JSON dict. Accepts:

        1. **Our native format** — `{"format": "fd6.shapes", "version": 1, ...}`
           with named-field shapes (`{"type": "rotated_ellipse", "x": ..., "rx": ..., ...}`).

        2. **Legacy geometrize / forza-painter format** — no `format` key,
           shapes have integer type codes + a `data` array:
           `{"shapes": [{"type": 16, "data": [x,y,w,h,rot], "color": [r,g,b,a], "score": s}, ...]}`
           Painter's geometry_json.py uses RECTANGLE=1, ROTATED_ELLIPSE=16.
           The first shape is conventionally a background rectangle whose
           `data[2:4]` carries the source image size. Drawables in `shapes[1:]`
           use CENTER coordinates with FULL extents (we halve to our hw/hh,
           rx/ry convention). This is what `forza-painter`, geometrize-lib,
           and earlier FD6 / FD6-fork outputs produce — without compat the
           Upload JSON flow would reject any JSON not generated by our own
           pipeline.
        """
        fmt = data.get("format")
        if fmt is None and isinstance(data.get("shapes"), list):
            # No format key → likely legacy geometrize/painter. Two detection
            # paths so we report the right error class:
            #   - Empty shapes list: treat as legacy and let _from_legacy_
            #     geometrize raise its specific "empty shapes" error.
            #   - Non-empty: confirm signature (integer type + data array)
            #     before routing to the converter — avoids misclassifying
            #     a different shape-bearing format as legacy.
            shapes_raw = data.get("shapes", [])
            if not shapes_raw:
                return cls._from_legacy_geometrize(data)
            if isinstance(shapes_raw[0], dict) \
                    and isinstance(shapes_raw[0].get("type"), (int, float)) \
                    and isinstance(shapes_raw[0].get("data"), list):
                return cls._from_legacy_geometrize(data)
        if fmt != FD6_FORMAT:
            raise ValueError(f"Unsupported document format: {fmt!r} (expected {FD6_FORMAT!r})")
        ver = data.get("version")
        if ver != FD6_VERSION:
            raise ValueError(f"Unsupported document version: {ver!r} (expected {FD6_VERSION})")
        size = data.get("image_size", [0, 0])
        return cls(
            format=fmt,
            version=ver,
            source_image=str(data.get("source_image", "")),
            image_size=(int(size[0]), int(size[1])),
            shape_count=int(data.get("shape_count", len(data.get("shapes", [])))),
            generated_at=str(data.get("generated_at", "")),
            profile=str(data.get("profile", "")),
            sticker_mode=bool(data.get("sticker_mode", False)),
            shapes=list(data.get("shapes", [])),
        )

    # Painter integer type constants (forza-painter-fh6/src/geometry_json.py).
    _LEGACY_RECTANGLE = 1
    _LEGACY_ROTATED_ELLIPSE = 16

    @classmethod
    def _from_legacy_geometrize(cls, data: dict) -> "FD6Document":
        """Convert a geometrize / forza-painter JSON into our native format.

        Painter's convention (per their main.py:load_geometry + geometry_json.py):
          - shapes[0] is the background rectangle. data = [bg_x, bg_y, image_w, image_h];
            data[2:4] carries the canvas size. If color alpha > 0, the BG renders;
            we emit it as a centered rectangle covering the full canvas.
          - shapes[1:] are drawables. For type=1 (RECTANGLE) data=[x,y,w,h], x/y
            are CENTER and w/h are FULL extents — we halve to hw/hh. For
            type=16 (ROTATED_ELLIPSE) data=[x,y,w,h,rot] same convention plus
            rotation in degrees — we halve to rx/ry, pass angle through.
          - Color is uint8 [r,g,b,a]; transparent (a==0) shapes are skipped
            (matches painter's load behavior).
        """
        from datetime import datetime, timezone
        shapes_raw = list(data.get("shapes", []))
        if not shapes_raw:
            raise ValueError("legacy format: empty shapes array")

        # First shape is the background — extract canvas size from its data[2:4].
        bg = shapes_raw[0]
        bg_data = bg.get("data", [])
        if len(bg_data) < 4:
            raise ValueError(f"legacy format: BG shape data too short: {bg_data!r}")
        image_w = int(bg_data[2])
        image_h = int(bg_data[3])
        bg_color = bg.get("color", [0, 0, 0, 0])

        out_shapes: list[dict] = []
        # Re-emit the BG as a centered rectangle if visible. Matches painter's
        # main.py:222 — `if bg_a > 0: shapes.append(Shape(1, image_w//2, image_h//2,
        # image_w, image_h, 0, Color(...), False))`.
        if len(bg_color) >= 4 and int(bg_color[3]) > 0:
            out_shapes.append({
                "type": "rectangle",
                "x": image_w / 2.0,
                "y": image_h / 2.0,
                "hw": image_w / 2.0,
                "hh": image_h / 2.0,
                "color": [int(bg_color[0]), int(bg_color[1]),
                          int(bg_color[2]), int(bg_color[3])],
            })

        # Convert drawables.
        for s in shapes_raw[1:]:
            converted = cls._convert_legacy_shape(s)
            if converted is not None:
                out_shapes.append(converted)

        return cls(
            format=FD6_FORMAT,
            version=FD6_VERSION,
            source_image=str(data.get("source_image", "")),
            image_size=(image_w, image_h),
            shape_count=len(out_shapes),
            generated_at=datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
            profile="legacy-geometrize-import",
            # Legacy format has no sticker_mode flag — default to False.
            sticker_mode=False,
            shapes=out_shapes,
        )

    @classmethod
    def _convert_legacy_shape(cls, s: dict) -> dict | None:
        """Convert ONE legacy shape (integer type + data array) to our
        native named-field schema. Returns None on unsupported types or
        invisible (alpha=0) shapes — caller should skip None entries."""
        if not isinstance(s, dict):
            return None
        try:
            t = int(s.get("type", -1))
        except (TypeError, ValueError):
            return None
        color = s.get("color", [])
        if not isinstance(color, list) or len(color) < 4:
            return None
        # Skip transparent shapes — matches painter's load (main.py:227).
        if int(color[3]) <= 0:
            return None
        d = s.get("data", [])
        if not isinstance(d, list) or len(d) < 4:
            return None
        rgba = [int(color[0]) & 0xFF, int(color[1]) & 0xFF,
                int(color[2]) & 0xFF, int(color[3]) & 0xFF]
        if t == cls._LEGACY_RECTANGLE:
            # Painter RECTANGLE: data=[x,y,w,h], x/y CENTER, w/h FULL extents.
            x, y, w, h = float(d[0]), float(d[1]), float(d[2]), float(d[3])
            return {
                "type": "rectangle",
                "x": x, "y": y,
                "hw": w / 2.0, "hh": h / 2.0,
                "color": rgba,
            }
        if t == cls._LEGACY_ROTATED_ELLIPSE:
            # data=[x,y,w,h,rot], x/y CENTER, w/h FULL extents, rot degrees.
            if len(d) < 5:
                return None
            x, y, w, h, rot = (float(d[0]), float(d[1]), float(d[2]),
                                float(d[3]), float(d[4]))
            return {
                "type": "rotated_ellipse",
                "x": x, "y": y,
                "rx": w / 2.0, "ry": h / 2.0,
                "angle": rot,
                "color": rgba,
            }
        # Unsupported legacy type (geometrize has more shape kinds — triangle,
        # circle, ellipse-non-rotated etc — but painter only handles 1 + 16
        # for FH6 vinyl injection, so neither does the legacy compat path).
        return None

    def materialize_shapes(self) -> list[Shape]:
        return [shape_from_json(s) for s in self.shapes]

    @classmethod
    def from_engine(
        cls,
        source_image: str,
        image_size: tuple[int, int],
        shapes: Iterable[Shape],
        profile_name: str = "",
        sticker_mode: bool = False,
    ) -> "FD6Document":
        shape_list = [s.to_json() for s in shapes]
        return cls(
            format=FD6_FORMAT,
            version=FD6_VERSION,
            source_image=source_image,
            image_size=image_size,
            shape_count=len(shape_list),
            generated_at=datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
            profile=profile_name,
            sticker_mode=sticker_mode,
            shapes=shape_list,
        )
